site_name: Austin Open Mic Poetry

theme:
  name: material
  favicon: images/mic-image.png
  palette:
    primary: green

nav:
  - Open Mic List: index.md
#  - Sunday: sunday.md
  - Mondays: monday.md
#  - Wednesdays: wednesday.md
  - Thursdays: thursday.md
  - Fridays: friday.md
#  - Writers League: writers-league.md
  - Record Collectors: record-collectors.md
#  - Poetry Archives: poetry-archives/expressions.md
  - Local Bookstores We Love: book-stores.md
  - Local Poets We Love: poets.md
  - Contact Us: contact.md