site_name: Austin Open Mic Poetry

theme:
  name: material
  favicon: images/mic-image.png
  palette:
    primary: green

nav:
  - Open Mic List: index.md
  - Record Collectors: record-collectors.md
#  - Sunday: sunday.md
  - Monday: monday.md
  - Thursdays: thursday.md
  - Fridays: friday.md