site_name: Austin Open Mic Poetry

theme:
  name: material
  favicon: images/mic-image.png
  palette:
    primary: green

nav:
  - Home: index.md
#  - Sunday: day-specific/sunday.md
#  - Monday: day-specific/monday.md
#  - Thursday: day-specific/thursday.md
#  - Friday: day-specific/friday.md